// Main.java
// Entry point for the MiniLang+ compiler front end (CSC 340 - Second Term 2025-26)
//
// This file ties the lexer and parser together. It:
//   1. Reads a MiniLang+ source file from the command line argument
//   2. Runs the lexer and prints all tokens
//   3. Runs the parser and checks for syntax errors
//   4. Prints a formatted parse tree if the program is valid
//
// Usage:
//   javac *.java
//   java Main <filename>
//   Example: java Main test1_valid.ml

// THIS FILE WAS COMPLETLY GENERATED BY AI
import org.antlr.v4.runtime.*;
import org.antlr.v4.runtime.tree.*;
import java.io.*;
import java.util.*;

public class Main {

    // ─── ANSI color codes for terminal output ────────────────────────────────
    // These make the output easier to read by color-coding different elements.
    // If your terminal doesn't support colors, they are safely ignored.
    static final String RESET  = "\u001B[0m";
    static final String BOLD   = "\u001B[1m";
    static final String RED    = "\u001B[31m";
    static final String GREEN  = "\u001B[32m";
    static final String YELLOW = "\u001B[33m";
    static final String CYAN   = "\u001B[36m";
    static final String GRAY   = "\u001B[90m";

    public static void main(String[] args) throws IOException {

        // ── 1. Check that a file argument was provided ──────────────────────
        if (args.length == 0) {
            System.err.println(RED + "Usage: java Main <filename>" + RESET);
            System.err.println("Example: java Main test1_valid.ml");
            System.exit(1);
        }

        String filename = args[0];
        File file = new File(filename);

        if (!file.exists()) {
            System.err.println(RED + "Error: file not found: " + filename + RESET);
            System.exit(1);
        }

        // ── 2. Print header ─────────────────────────────────────────────────
        printSeparator();
        System.out.println(BOLD + "  MiniLang+ Compiler Front End" + RESET);
        System.out.println(GRAY + "  File: " + filename + RESET);
        printSeparator();

        // ── 3. Set up ANTLR input stream from the source file ───────────────
        CharStream input = CharStreams.fromFileName(filename);

        // ── 4. Run the Lexer and print the token stream ─────────────────────
        System.out.println("\n" + BOLD + CYAN + "[ PHASE 1 — LEXICAL ANALYSIS ]" + RESET + "\n");

        MiniLangLexer lexer = new MiniLangLexer(input);

        // Attach a custom error listener to the lexer so we can count errors
        ErrorListener lexerErrors = new ErrorListener();
        lexer.removeErrorListeners();           // remove default console listener
        lexer.addErrorListener(lexerErrors);

        // Print token table header
        System.out.printf(GRAY + "  %-6s %-16s %-20s %s%n" + RESET,
                "Index", "Type", "Value", "Line:Col");
        System.out.println(GRAY + "  " + "─".repeat(58) + RESET);

        // Collect all tokens (we need them twice — once for printing, once for parser)
        CommonTokenStream tokenStream = new CommonTokenStream(lexer);
        tokenStream.fill(); // force all tokens to be loaded

        List<Token> tokens = tokenStream.getTokens();
        for (Token token : tokens) {
            // Skip the EOF token for cleaner display (we print it separately)
            if (token.getType() == Token.EOF) continue;

            String typeName  = MiniLangLexer.VOCABULARY.getDisplayName(token.getType());
            String value     = token.getText();
            String position  = token.getLine() + ":" + token.getCharPositionInLine();
            String color     = getTokenColor(typeName);

            System.out.printf("  %-6s " + color + "%-16s" + RESET + " %-20s " + GRAY + "%s" + RESET + "%n",
                    "@" + token.getTokenIndex(),
                    typeName,
                    "'" + value + "'",
                    position);
        }

        // Print EOF
        System.out.println(GRAY + "  " + "─".repeat(58) + RESET);
        System.out.printf(GRAY + "  %-6s %-16s %-20s%n" + RESET,
                "@" + (tokens.size()-1), "EOF", "<EOF>");

        // Lexer summary
        int tokenCount = tokens.size() - 1; // exclude EOF
        System.out.println();
        if (lexerErrors.getErrorCount() == 0) {
            System.out.println("  " + GREEN + "✓ Lexer: " + tokenCount + " tokens, no errors" + RESET);
        } else {
            System.out.println("  " + RED + "✗ Lexer: " + lexerErrors.getErrorCount() + " error(s) found" + RESET);
        }

        // ── 5. Run the Parser and print the parse tree ──────────────────────
        System.out.println("\n" + BOLD + CYAN + "[ PHASE 2 — SYNTAX ANALYSIS ]" + RESET + "\n");

        // Reset the token stream so the parser reads from the beginning
        tokenStream.seek(0);

        MiniLangParser parser = new MiniLangParser(tokenStream);

        // Attach a custom error listener to the parser
        ErrorListener parserErrors = new ErrorListener();
        parser.removeErrorListeners();
        parser.addErrorListener(parserErrors);

        // Parse starting from the top-level rule: program
        ParseTree tree = parser.program();

        if (parserErrors.getErrorCount() == 0) {
            // Valid program — print the parse tree
            System.out.println("  " + GREEN + "✓ Parser: program is syntactically valid" + RESET);
            System.out.println("\n" + BOLD + CYAN + "[ PARSE TREE ]" + RESET + "\n");
            printTree(tree, parser, "", true);
        } else {
            // Invalid program — errors were already printed by the error listener
            System.out.println("  " + RED + "✗ Parser: " + parserErrors.getErrorCount() + " syntax error(s) found" + RESET);
        }

        // ── 6. Final summary ────────────────────────────────────────────────
        printSeparator();
        int totalErrors = lexerErrors.getErrorCount() + parserErrors.getErrorCount();
        if (totalErrors == 0) {
            System.out.println(GREEN + "  RESULT: Program accepted ✓" + RESET);
        } else {
            System.out.println(RED + "  RESULT: Program rejected — " + totalErrors + " error(s)" + RESET);
        }
        printSeparator();
        System.out.println();
    }

    // ─── Recursively print the parse tree in a readable indented format ──────
    // Each node shows the rule name (for parser rules) or the token value
    // (for terminal/leaf nodes). Indentation shows the tree structure.
    static void printTree(ParseTree tree, MiniLangParser parser, String indent, boolean isLast) {
        // Choose the branch character based on whether this is the last child
        String branch = isLast ? "└── " : "├── ";
        String childIndent = indent + (isLast ? "    " : "│   ");

        if (tree instanceof TerminalNode) {
            // Leaf node — print the actual token value
            Token token = ((TerminalNode) tree).getSymbol();
            if (token.getType() == Token.EOF) return; // skip EOF in tree display
            String typeName = MiniLangLexer.VOCABULARY.getDisplayName(token.getType());
            String color = getTokenColor(typeName);
            System.out.println(GRAY + indent + branch + RESET +
                    color + typeName + RESET +
                    GRAY + " '" + token.getText() + "'" + RESET);
        } else {
            // Internal node — print the grammar rule name
            String ruleName = tree instanceof RuleContext
                    ? parser.getRuleNames()[((RuleContext) tree).getRuleIndex()]
                    : tree.getClass().getSimpleName();
            System.out.println(GRAY + indent + branch + RESET +
                    BOLD + YELLOW + ruleName + RESET);

            // Recursively print all children
            int childCount = tree.getChildCount();
            for (int i = 0; i < childCount; i++) {
                printTree(tree.getChild(i), parser, childIndent, i == childCount - 1);
            }
        }
    }

    // ─── Assign colors to token types for readability ────────────────────────
    static String getTokenColor(String typeName) {
        switch (typeName) {
            case "'if'": case "'else'": case "'while'":
            case "'for'": case "'print'":
                return CYAN;        // keywords in cyan
            case "ID":
                return GREEN;       // identifiers in green
            case "INT":
                return YELLOW;      // numbers in yellow
            case "'='":
                return "\u001B[35m"; // assignment in magenta
            default:
                return RESET;       // everything else default
        }
    }

    // ─── Helper to print a horizontal separator line ─────────────────────────
    static void printSeparator() {
        System.out.println(GRAY + "  " + "═".repeat(58) + RESET);
    }

    // ─── Custom ANTLR error listener ─────────────────────────────────────────
    // ANTLR's default listener just prints errors to stderr without formatting.
    // This listener formats errors nicely and counts them so we can report them.
    static class ErrorListener extends BaseErrorListener {
        private int errorCount = 0;

        @Override
        public void syntaxError(Recognizer<?, ?> recognizer,
                                Object offendingSymbol,
                                int line,
                                int charPositionInLine,
                                String msg,
                                RecognitionException e) {
            errorCount++;
            System.out.println("  " + RED + "✗ Error at line " + line +
                    ":" + charPositionInLine + " — " + msg + RESET);
        }

        public int getErrorCount() { return errorCount; }
    }
}
